-   id: runway-test
    name: Runway test
    description: Runs runway test on cli
    entry: runway.sh
    language: script

-   id: runway-test-pipenv
    name: Runway test via pipenv
    description: Runs runway test in pipenv
    entry: punway-pipenv.sh
    language: script