# -   id: runway-test
#     name: Runway test
#     description: Runs runway test on cli
#     entry: runway
#     args: [test]
#     language: system

# -   id: runway-test-pipenv
#     name: Runway test via pipenv
#     description: Runs runway test in pipenv
#     entry: pipenv run runway test
#     language: system

-   id: runway-test
    name: Runway test
    description: Runs runway test on cli
    entry: runway.sh
    args: [test]
    language: script

-   id: runway-test-pipenv
    name: Runway test via pipenv
    description: Runs runway test in pipenv
    entry: runway-pipenv.sh
    language: script