-   id: runway-test
    name: Runway test
    description: Runs runway test on cli
    system: runway test
    language: script

-   id: runway-test-pipenv
    name: Runway test via pipenv
    description: Runs runway test in pipenv
    system: pipenv run runway test
    language: script